language: cpp
compiler: gcc
os: linux
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - libboost-dev
    - libboost-program-options-dev
    - libmuparser-dev
env:
  - CUDA_VERSION_MAJOR="8.0"
    CUDA_VERSION="8.0.61-1"
    CUB_VERSION="1.6.4"
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - mkdir 3rdparty
install:
  # Install CMake 3.8.0
  - wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz;
    tar xf cmake-3.8.0-Linux-x86_64.tar.gz;
    sudo cp -r cmake-3.8.0-Linux-x86_64/* /usr;
  # Install CUDA
  - wget "http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_${CUDA_VERSION}_amd64.deb";
    sudo dpkg -i cuda-repo-ubuntu1404_${CUDA_VERSION}_amd64.deb;
    sudo apt-get update;
    sudo apt-get install -y cuda-{core,cudart-dev,cufft-dev,curand-dev}-${CUDA_VERSION_MAJOR};
  # Install CUB
  - wget "https://github.com/NVlabs/cub/archive/${CUB_VERSION}.zip";
    unzip ${CUB_VERSION}.zip -d 3rdparty;
    ln -s cub-${CUB_VERSION} 3rdparty/cub;
before_script:
  - mkdir build;
    cd build;
  - export CUDACXX="/usr/local/cuda-${CUDA_VERSION_MAJOR}/bin/nvcc";
script:
  - cmake ..
  - make
